// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ErrorCountLessThanFive() {
  return window['go']['main']['App']['ErrorCountLessThanFive']();
}

export function GetErrorCount() {
  return window['go']['main']['App']['GetErrorCount']();
}

export function GetInternalIP() {
  return window['go']['main']['App']['GetInternalIP']();
}

export function GetPingCount() {
  return window['go']['main']['App']['GetPingCount']();
}

export function IncrementErrorCount() {
  return window['go']['main']['App']['IncrementErrorCount']();
}

export function MakeWindowsTaskIconFlash(arg1) {
  return window['go']['main']['App']['MakeWindowsTaskIconFlash'](arg1);
}

export function ResetErrorCount() {
  return window['go']['main']['App']['ResetErrorCount']();
}

export function SendDesktopNotification(arg1, arg2) {
  return window['go']['main']['App']['SendDesktopNotification'](arg1, arg2);
}

export function SendManualPing() {
  return window['go']['main']['App']['SendManualPing']();
}

export function SetInternalIP(arg1) {
  return window['go']['main']['App']['SetInternalIP'](arg1);
}

export function SetPingCount(arg1) {
  return window['go']['main']['App']['SetPingCount'](arg1);
}
