// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInternalIP():Promise<string>;

export function GetPingCount():Promise<number>;

export function MakeWindowsTaskIconFlash(arg1:string):Promise<void>;

export function SendDesktopNotification(arg1:string,arg2:string):Promise<void>;

export function SendManualPing():Promise<void>;

export function SetInternalIP(arg1:string):Promise<void>;

export function SetPingCount(arg1:number):Promise<void>;
