// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInternalIP() {
  return window['go']['main']['App']['GetInternalIP']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetInternalIP(arg1) {
  return window['go']['main']['App']['SetInternalIP'](arg1);
}
