// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ErrorCountLessThanFive():Promise<boolean>;

export function EvalAutoCurl():Promise<void>;

export function GetAutoCurl():Promise<boolean>;

export function GetErrorCount():Promise<number>;

export function GetInternalIP():Promise<string>;

export function GetInternalPort():Promise<string>;

export function GetPingCount():Promise<number>;

export function IncrementErrorCount():Promise<void>;

export function MakeWindowsTaskIconFlash(arg1:string):Promise<void>;

export function ResetErrorCount():Promise<void>;

export function SendDesktopNotification(arg1:string,arg2:string):Promise<void>;

export function SendManualCurl():Promise<void>;

export function SendManualPing():Promise<void>;

export function SetAutoCurl(arg1:boolean):Promise<void>;

export function SetInternalIP(arg1:string):Promise<void>;

export function SetInternalPort(arg1:string):Promise<void>;

export function SetPingCount(arg1:number):Promise<void>;
